import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.ResultSet;



/**
 *
 * @author lab-mmda
*/
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        itmCadastroDepartamento = new javax.swing.JMenu();
        itmCadastrarDepartamentos = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        itmExcluirDepartamento = new javax.swing.JMenuItem();
        itmListarDepartamento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itmCadastrarUsuarios = new javax.swing.JMenuItem();
        itmAlterarUsuarios = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        itmExcluirUsuarios = new javax.swing.JMenuItem();
        itmListarUsuarios = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        getContentPane().setLayout(null);

        itmCadastroDepartamento.setMnemonic('D');
        itmCadastroDepartamento.setText("Departamentos");

        itmCadastrarDepartamentos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmCadastrarDepartamentos.setText("Cadastrar");
        itmCadastrarDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarDepartamentosActionPerformed(evt);
            }
        });
        itmCadastroDepartamento.add(itmCadastrarDepartamentos);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Alterar");
        itmCadastroDepartamento.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Consultar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        itmCadastroDepartamento.add(jMenuItem3);

        itmExcluirDepartamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmExcluirDepartamento.setText("Exluir");
        itmExcluirDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirDepartamentoActionPerformed(evt);
            }
        });
        itmCadastroDepartamento.add(itmExcluirDepartamento);

        itmListarDepartamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmListarDepartamento.setText("Listar");
        itmListarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarDepartamentoActionPerformed(evt);
            }
        });
        itmCadastroDepartamento.add(itmListarDepartamento);

        jMenuBar1.add(itmCadastroDepartamento);

        jMenu2.setMnemonic('F');
        jMenu2.setText("Funcionários");

        jMenuItem6.setText("Cadastrar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Alterar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Consultar");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Excluir");
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("Listar");
        jMenu2.add(jMenuItem10);

        jMenuBar1.add(jMenu2);

        jMenu3.setMnemonic('P');
        jMenu3.setText("Produtos");

        jMenuItem11.setText("Cadastrar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem12.setText("Alterar");
        jMenu3.add(jMenuItem12);

        jMenuItem13.setText("Consular");
        jMenu3.add(jMenuItem13);

        jMenuItem14.setText("Excluir");
        jMenu3.add(jMenuItem14);

        jMenuItem15.setText("Listar");
        jMenu3.add(jMenuItem15);

        jMenuBar1.add(jMenu3);

        jMenu4.setMnemonic('U');
        jMenu4.setText("Usuários");

        itmCadastrarUsuarios.setText("Cadastrar");
        itmCadastrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarUsuariosActionPerformed(evt);
            }
        });
        jMenu4.add(itmCadastrarUsuarios);

        itmAlterarUsuarios.setText("Alterar");
        itmAlterarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarUsuariosActionPerformed(evt);
            }
        });
        jMenu4.add(itmAlterarUsuarios);

        jMenuItem18.setText("Consultar");
        jMenu4.add(jMenuItem18);

        itmExcluirUsuarios.setText("Excluir");
        itmExcluirUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirUsuariosActionPerformed(evt);
            }
        });
        jMenu4.add(itmExcluirUsuarios);

        itmListarUsuarios.setText("Listar");
        itmListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarUsuariosActionPerformed(evt);
            }
        });
        jMenu4.add(itmListarUsuarios);

        jMenuBar1.add(jMenu4);

        jMenu5.setMnemonic('A');
        jMenu5.setText("Ajuda");

        jMenuItem21.setText("Cadastrar");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem21);

        jMenuItem22.setText("Alterar");
        jMenu5.add(jMenuItem22);

        jMenuItem23.setText("Consultar");
        jMenu5.add(jMenuItem23);

        jMenuItem24.setText("Excluir");
        jMenu5.add(jMenuItem24);

        jMenuItem25.setText("Listar");
        jMenu5.add(jMenuItem25);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(378, 246));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void itmCadastrarDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarDepartamentosActionPerformed
        new CadastroDepartamento().setVisible(true);
    }//GEN-LAST:event_itmCadastrarDepartamentosActionPerformed

    private void itmCadastrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarUsuariosActionPerformed

        new CadastrarUsuario().setVisible(true);
    }//GEN-LAST:event_itmCadastrarUsuariosActionPerformed

    private void itmExcluirUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirUsuariosActionPerformed
        // 1- perguntar qual usuário excluir
        String u;
        u = JOptionPane.showInputDialog("Qual Nome deseja excluir ?");
        // 2- conectar com banco de dados MYSQL
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","Gabriel741");
            //3- Excluir usuário digitado da tabela do DB
            PreparedStatement st = conectado.prepareStatement("DELETE FROM usuarios WHERE usuario = ?");
            st.setString(1, u);

            int resultado = st.executeUpdate(); // Executa o DELETE
            if (resultado == 1) {
                // 4- Mostrar uma mensagem indicando que excluiu
                JOptionPane.showMessageDialog(null, "usuarios excluído com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "usuarios não cadastrado");
            }

        } catch (ClassNotFoundException ex) {

            JOptionPane.showMessageDialog(null, "driver não colocado no library");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro no dados do banco de dados" + ex.getMessage());
        }        
    }//GEN-LAST:event_itmExcluirUsuariosActionPerformed

    private void itmListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarUsuariosActionPerformed
        new ListaUsuarios().setVisible(true);
    }//GEN-LAST:event_itmListarUsuariosActionPerformed

    private void itmExcluirDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirDepartamentoActionPerformed
        // 1- perguntar qual usuário excluir
        String d;
        d = JOptionPane.showInputDialog("Qual ID excluir ?");
        // 2- conectar com banco de dados MYSQL
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","Gabriel741");
            //3- Excluir usuário digitado da tabela do DB
            PreparedStatement st = conectado.prepareStatement("DELETE FROM Departamento WHERE ID = ?");
            st.setString(1, d);

            int resultado = st.executeUpdate(); // Executa o DELETE
            if (resultado == 1) {
                // 4- Mostrar uma mensagem indicando que excluiu
                JOptionPane.showMessageDialog(null, "Departamento excluido com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Departamento nao cadastrado");
            }

        } catch (ClassNotFoundException ex) {

            JOptionPane.showMessageDialog(null, "driver não colocado no library");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro no dados do banco de dados" + ex.getMessage());
        }
    }//GEN-LAST:event_itmExcluirDepartamentoActionPerformed

    private void itmListarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarDepartamentoActionPerformed
  new ListaDepartamento().setVisible(true);     
    }//GEN-LAST:event_itmListarDepartamentoActionPerformed

    private void itmAlterarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarUsuariosActionPerformed
        new AlterarUsuarios().setVisible(true);
    }//GEN-LAST:event_itmAlterarUsuariosActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAlterarUsuarios;
    private javax.swing.JMenuItem itmCadastrarDepartamentos;
    private javax.swing.JMenuItem itmCadastrarUsuarios;
    private javax.swing.JMenu itmCadastroDepartamento;
    private javax.swing.JMenuItem itmExcluirDepartamento;
    private javax.swing.JMenuItem itmExcluirUsuarios;
    private javax.swing.JMenuItem itmListarDepartamento;
    private javax.swing.JMenuItem itmListarUsuarios;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
     }
